max_width = 80
fn_call_width = 80
single_line_if_else_max_width = 80
comment_width = 80
wrap_comments = false

struct_field_align_threshold = 30
struct_lit_width = 80
struct_variant_width = 80

use_try_shorthand = true
fn_single_line = true
force_format_strings = true
reorder_imported_names = true
reorder_imports = true
condense_wildcard_suffices = true

