max_width = 100
comment_width = 100
wrap_comments = true

merge_imports = true
reorder_impl_items = true
use_field_init_shorthand = true

struct_field_align_threshold = 30

use_try_shorthand = true
fn_single_line = true

